# Generated by Django 6.0 on 2025-12-16 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tamanho',
            new_name='size',
        ),
    ]
