# Generated by Django 6.0 on 2025-12-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_tamanho_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='products/static', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_height',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image_width',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
